[target.aarch64-linux-android]
rustflags = ["-C", "opt-level=3"]

[target.armv7-linux-androideabi]
rustflags = ["-C", "opt-level=3"]

[target.x86_64-linux-android]
rustflags = ["-C", "opt-level=3"]

[target.i686-linux-android]
rustflags = ["-C", "opt-level=3"]
