name: Build Rust Natives
on:
  workflow_dispatch:


concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Setup Java
        uses: actions/setup-java@main
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6

      - name: Cache cargo
        uses: actions/cache@v4
        with:
          path: ${{ github.workspace }}/common/build/cargo
          key: ${{ runner.os }}-node-${{ hashFiles('common/src/main/rust/**/Cargo.lock') }}

      - name: Setup cargo-ndk
        run: |
          cargo install cargo-ndk
  
      - name: Run Gradle Task
        run: ./gradlew common:buildRustNatives

      - name: Upload Artifacts
        uses: actions/upload-artifact@main
        with:
          name: android-natives
          path: target/android
