name: Release
on: [workflow_dispatch] # Manual trigger

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@main
      - name: Setup Java
        uses: actions/setup-java@main
        with:
          distribution: 'temurin'
          java-version: 21
          cache: gradle
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@main
      - name: Make Gradle Wrapper Executable
        run: chmod +x ./gradlew
      - name: Execute Gradle build
        run: ./gradlew build

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v7.0.1
        with:
          # Artifact name. If the `archive` input is `false`, the name of the file uploaded will be the artifact name.
          name: sable-java# optional, default is artifact
          # A file, directory or wildcard pattern that describes what to upload.
          path: |
                **/*sable*.jar
